#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : kalarm
Version  : 18.12.2
Release  : 4
URL      : https://download.kde.org/stable/applications/18.12.2/src/kalarm-18.12.2.tar.xz
Source0  : https://download.kde.org/stable/applications/18.12.2/src/kalarm-18.12.2.tar.xz
Source99 : https://download.kde.org/stable/applications/18.12.2/src/kalarm-18.12.2.tar.xz.sig
Summary  : Personal alarm scheduler
Group    : Development/Tools
License  : BSD-3-Clause GFDL-1.2 GPL-2.0 LGPL-2.1
Requires: kalarm-bin = %{version}-%{release}
Requires: kalarm-data = %{version}-%{release}
Requires: kalarm-license = %{version}-%{release}
Requires: kalarm-locales = %{version}-%{release}
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : akonadi-mime-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : gpgme-dev
BuildRequires : kalarmcal-dev
BuildRequires : kcalcore-dev
BuildRequires : kcalutils-dev
BuildRequires : kcontacts-dev
BuildRequires : kdepim-apps-libs-dev
BuildRequires : kglobalaccel-dev
BuildRequires : kholidays-dev
BuildRequires : kidentitymanagement-dev
BuildRequires : kimap-dev
BuildRequires : kmailtransport-dev
BuildRequires : kmime-dev
BuildRequires : kpimtextedit-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : libkdepim-dev
BuildRequires : libkleo-dev
BuildRequires : mailcommon-dev
BuildRequires : messagelib-dev
BuildRequires : phonon-dev
BuildRequires : pimcommon-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtx11extras-dev

%description
KAlarm
======
KAlarm is a personal alarm message, audio, command and email scheduler.

%package bin
Summary: bin components for the kalarm package.
Group: Binaries
Requires: kalarm-data = %{version}-%{release}
Requires: kalarm-license = %{version}-%{release}

%description bin
bin components for the kalarm package.


%package data
Summary: data components for the kalarm package.
Group: Data

%description data
data components for the kalarm package.


%package doc
Summary: doc components for the kalarm package.
Group: Documentation

%description doc
doc components for the kalarm package.


%package license
Summary: license components for the kalarm package.
Group: Default

%description license
license components for the kalarm package.


%package locales
Summary: locales components for the kalarm package.
Group: Default

%description locales
locales components for the kalarm package.


%prep
%setup -q -n kalarm-18.12.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549936744
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1549936744
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kalarm
cp COPYING %{buildroot}/usr/share/package-licenses/kalarm/COPYING
cp COPYING.DOC %{buildroot}/usr/share/package-licenses/kalarm/COPYING.DOC
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/kalarm/COPYING.LIB
cp cmake/modules/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/kalarm/cmake_modules_COPYING-CMAKE-SCRIPTS
pushd clr-build
%make_install
popd
%find_lang kalarm

%files
%defattr(-,root,root,-)
/usr/lib64/libexec/kauth/kalarm_helper

%files bin
%defattr(-,root,root,-)
/usr/bin/kalarm
/usr/bin/kalarmautostart

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kalarm.desktop
/usr/share/config.kcfg/kalarmconfig.kcfg
/usr/share/dbus-1/interfaces/org.kde.kalarm.kalarm.xml
/usr/share/dbus-1/system-services/org.kde.kalarm.rtcwake.service
/usr/share/dbus-1/system.d/org.kde.kalarm.rtcwake.conf
/usr/share/icons/hicolor/128x128/apps/kalarm.png
/usr/share/icons/hicolor/16x16/apps/kalarm.png
/usr/share/icons/hicolor/22x22/apps/kalarm.png
/usr/share/icons/hicolor/32x32/apps/kalarm.png
/usr/share/icons/hicolor/48x48/apps/kalarm.png
/usr/share/icons/hicolor/64x64/apps/kalarm.png
/usr/share/kalarm/icons/oxygen/16x16/actions/document-new-from-template.png
/usr/share/kalarm/icons/oxygen/16x16/actions/new-audio-alarm.png
/usr/share/kalarm/icons/oxygen/16x16/actions/new-command-alarm.png
/usr/share/kalarm/icons/oxygen/22x22/actions/document-new-from-template.png
/usr/share/kalarm/icons/oxygen/22x22/actions/kalarm-disabled.png
/usr/share/kalarm/icons/oxygen/22x22/actions/kalarm-partdisabled.png
/usr/share/kalarm/icons/oxygen/22x22/actions/kalarm.png
/usr/share/kalarm/icons/oxygen/22x22/actions/new-audio-alarm.png
/usr/share/kalarm/icons/oxygen/22x22/actions/new-command-alarm.png
/usr/share/kconf_update/kalarm-1.2.1-general.pl
/usr/share/kconf_update/kalarm-1.9.5-defaults.pl
/usr/share/kconf_update/kalarm-15.08-kickoff.sh
/usr/share/kconf_update/kalarm-2.0.2-general.pl
/usr/share/kconf_update/kalarm-2.1.5-general.pl
/usr/share/kconf_update/kalarm-version.pl
/usr/share/kconf_update/kalarm.upd
/usr/share/kxmlgui5/kalarm/kalarmui.rc
/usr/share/metainfo/org.kde.kalarm.appdata.xml
/usr/share/polkit-1/actions/org.kde.kalarm.rtcwake.policy
/usr/share/xdg/autostart/kalarm.autostart.desktop
/usr/share/xdg/kalarm.categories
/usr/share/xdg/kalarm.renamecategories

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kalarm/alarmmessage.png
/usr/share/doc/HTML/ca/kalarm/editwindow-simple.png
/usr/share/doc/HTML/ca/kalarm/editwindow.png
/usr/share/doc/HTML/ca/kalarm/index.cache.bz2
/usr/share/doc/HTML/ca/kalarm/index.docbook
/usr/share/doc/HTML/ca/kalarm/mainwindow-calendars.png
/usr/share/doc/HTML/ca/kalarm/mainwindow.png
/usr/share/doc/HTML/ca/kalarm/spinbox.png
/usr/share/doc/HTML/de/kalarm/index.cache.bz2
/usr/share/doc/HTML/de/kalarm/index.docbook
/usr/share/doc/HTML/en/kalarm/alarmmessage.png
/usr/share/doc/HTML/en/kalarm/editwindow-simple.png
/usr/share/doc/HTML/en/kalarm/editwindow.png
/usr/share/doc/HTML/en/kalarm/index.cache.bz2
/usr/share/doc/HTML/en/kalarm/index.docbook
/usr/share/doc/HTML/en/kalarm/mainwindow-calendars.png
/usr/share/doc/HTML/en/kalarm/mainwindow.png
/usr/share/doc/HTML/en/kalarm/spinbox.png
/usr/share/doc/HTML/es/kalarm/index.cache.bz2
/usr/share/doc/HTML/es/kalarm/index.docbook
/usr/share/doc/HTML/et/kalarm/index.cache.bz2
/usr/share/doc/HTML/et/kalarm/index.docbook
/usr/share/doc/HTML/it/kalarm/index.cache.bz2
/usr/share/doc/HTML/it/kalarm/index.docbook
/usr/share/doc/HTML/nl/kalarm/index.cache.bz2
/usr/share/doc/HTML/nl/kalarm/index.docbook
/usr/share/doc/HTML/pt/kalarm/index.cache.bz2
/usr/share/doc/HTML/pt/kalarm/index.docbook
/usr/share/doc/HTML/pt_BR/kalarm/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kalarm/index.docbook
/usr/share/doc/HTML/sv/kalarm/index.cache.bz2
/usr/share/doc/HTML/sv/kalarm/index.docbook
/usr/share/doc/HTML/uk/kalarm/index.cache.bz2
/usr/share/doc/HTML/uk/kalarm/index.docbook

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kalarm/COPYING
/usr/share/package-licenses/kalarm/COPYING.DOC
/usr/share/package-licenses/kalarm/COPYING.LIB
/usr/share/package-licenses/kalarm/cmake_modules_COPYING-CMAKE-SCRIPTS

%files locales -f kalarm.lang
%defattr(-,root,root,-)

